name = "story_bakery/user_input_manager"
version = "0.1.0"
license = "MIT"
includes = [
    "pesde.toml",
    "LICENSE",
    "README.md",
    ".pesde/scripts/roblox_sync_config_generator.luau",
    ".pesde/scripts/sourcemap_generator.luau",
    "src/**/*.luau",
    "src/**/*.json",
    "tests/**/*.luau",
]

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dependencies]
KeyStore = { repo = "Story-Bakery/KeyStore", rev = "main" }
Maid = { repo = "Story-Bakery/Maid", rev = "main" }
Signal = { repo = "Story-Bakery/Signal", rev = "main" }
TableUtil = { repo = "Story-Bakery/TableUtil", rev = "main" }

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"

[engines]
pesde = "^0.7.0"
lune = "^0.10.2"
